=== Luka-Sever/Otvoreno-ra-unarstvo/schema.json
{
   "$schema": "http://json-schema.org/draft-07/schema#",
   "$id": "https://github.com/Luka-Sever/Otvoreno-ra-unarstvo/schema.json",
   "type" : "array",
   "title": "Popis satelita koji kruže Zemljom",
   "description" : "Popis nekih satelita koji kruže Zemljom sa najčešćim svojstvima.",
     "items": {
    "type": "object",
    "properties": {
      "ime satelita": {
        "type": "string"
      },
      "drzava porijekla": {
        "type": "string"
      },
      "drzava odrzavanja": {
        "type": "string"
      },
      "vlasnik": {
        "type": "string"
      },
      "korist": {
        "type": "string"
      },
      "svrha": {
        "type": "string"
      },
      "orbita": {
        "type": "string"
      },
      "apside": {
        "type": "object",
        "properties": {
          "perigej": {
            "type": "number"
          },
          "apogej": {
            "type": "number"
          }
        },
        "required": [
          "perigej",
          "apogej"
        ]
      },
      "inklinacija": {
        "type": "number"
      },
      "period": {
        "type": "number"
      }
    },
    "required": [
      "ime satelita",
      "drzava porijekla",
      "drzava odrzavanja",
      "vlasnik",
      "korist",
      "svrha",
      "orbita",
      "apside",
      "inklinacija",
      "period"
    ]
  }
}

=== Luka-Sever/Otvoreno-ra-unarstvo/sateliti.json
[
    {
        "ime satelita": "AprizeSat 4",
        "drzava porijekla": "SAD",
        "drzava odrzavanja": "SAD/Argentina",
        "vlasnik": "Aprize Satelliti, Argentina",
        "korist": "Komercijalna",
        "svrha": "Komunikacija/Pomorsko praćenje",
        "orbita": "LEO",
        "apside": {
            "perigej": 604.0,
            "apogej": 674.0
        },
        "inklinacija": 98.1,
        "period": 97.5
    },
    {
        "ime satelita": "Beidou DW 33",
        "drzava porijekla": "Kina",
        "drzava odrzavanja": "Kina",
        "vlasnik": "Chinese Ministry of National Defense",
        "korist": "Vojna/Vladina",
        "svrha": "Navigacija/Globalna navigacija",
        "orbita": "MEO",
        "apside": {
            "perigej": 21509.0,
            "apogej": 21545.0
        },
        "inklinacija": 55.0,
        "period": 773.2
    },
    {
        "ime satelita": "Kepler-11 DANEEL",
        "drzava porijekla": "NR (5/21)",
        "drzava odrzavanja": "Kanada",
        "vlasnik": "Kepler Communications",
        "korist": "Komercijalna",
        "svrha": "Komunikacija",
        "orbita": "LEO",
        "apside": {
            "perigej": 525.0,
            "apogej": 535.0
        },
        "inklinacija": 97.7,
        "period": 95.2
    },
    {
        "ime satelita": "Ladybird 2",
        "drzava porijekla": "NR",
        "drzava odrzavanja": "China",
        "vlasnik": "Beijing Commsat Technology Development Co. Ltd.",
        "korist": "Komercijalna",
        "svrha": "Unaprjeđivanje tehnologije",
        "orbita": "LEO",
        "apside": {
            "perigej": 530.0,
            "apogej": 549.0
        },
        "inklinacija": 97.6,
        "period": 95.4
    },
    {
        "ime satelita": "Lemur-2 AC-Cubed ",
        "drzava porijekla": "NR (9/21)",
        "drzava odrzavanja": "SAD",
        "vlasnik": "Spire Global Inc.",
        "korist": "Komercijalna",
        "svrha": "Obzervacija Zemlje",
        "orbita": "LEO",
        "apside": {
            "perigej": 512.0,
            "apogej": 533.0
        },
        "inklinacija": 97.5,
        "period": 95.2
    },
    {
        "ime satelita": "Mercury 3",
        "drzava porijekla": "SAD",
        "drzava odrzavanja": "SAD",
        "vlasnik": "National Reconnaissance Office (NRO)/US Air Force",
        "korist": "Vojna",
        "svrha": "Obzervacija Zemlje",
        "orbita": "GEO",
        "apside": {
            "perigej": 35500.0,
            "apogej": 35500.0
        },
        "inklinacija": 7.0,
        "period": 1436.0
    },
    {
        "ime satelita": "Meteosat 9",
        "drzava porijekla": "EUMETSAT",
        "drzava odrzavanja": "Multinacionalna",
        "vlasnik": "EUMETSAT (European Organization for the Exploitation of Meteorological Satellites)",
        "korist": "Vladina/Civili",
        "svrha": "Obzervacija Zemlje",
        "orbita": "GEO",
        "apside": {
            "perigej": 35775.0,
            "apogej": 35795.0
        },
        "inklinacija": 0.29,
        "period": 1436.0
    },
    {
        "ime satelita": "USA 262",
        "drzava porijekla": "SAD",
        "drzava odrzavanja": "SAD",
        "vlasnik": "DoD/US Air Force",
        "korist": "Vojna/Komercijalna",
        "svrha": "Navigacija/Globalna navigacija",
        "orbita": "MEO",
        "apside": {
            "perigej": 20446.0,
            "apogej": 20459.0
        },
        "inklinacija": 54.9,
        "period": 728.96
    },
    {
        "ime satelita": "PVSAT",
        "drzava porijekla": "NR (9/21)",
        "drzava odrzavanja": "Južna Koreja",
        "vlasnik": "Korean Aerospace Research Institute (KARI)",
        "korist": "Vladina",
        "svrha": "Technology Demonstration",
        "orbita": "LEO",
        "apside": {
            "perigej": 695.0,
            "apogej": 704.0
        },
        "inklinacija": 98.1,
        "period": 100.0
    },
    {
        "ime satelita": "RISat-2B",
        "drzava porijekla": "Indija",
        "drzava odrzavanja": "Indija",
        "vlasnik": "Ministry of Defense",
        "korist": "Vojna",
        "svrha": "Obzervacija Zemlje",
        "orbita": "LEO",
        "apside": {
            "perigej": 550.0,
            "apogej": 557.0
        },
        "inklinacija": 37.0,
        "period": 96.0
    }
]
