=== Luka-Sever/Otvoreno-ra-unarstvo/backend/shema_za_bazu.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Generated schema for Root",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "ime satelita": {
        "type": "string"
      },
      "drzava porijekla": {
        "type": "string"
      },
      "drzava odrzavanja": {
        "type": "string"
      },
      "vlasnik": {
        "type": "string"
      },
      "korist": {
        "type": "string"
      },
      "orbita": {
        "type": "string"
      },
      "inklinacija": {
        "type": "number"
      },
      "period": {
        "type": "number"
      },
      "svrha": {
        "type": "string"
      },
      "perigej": {
        "type": "number"
      },
      "apogej": {
        "type": "number"
      }
    },
    "required": [
      "ime satelita",
      "drzava porijekla",
      "drzava odrzavanja",
      "vlasnik",
      "korist",
      "orbita",
      "inklinacija",
      "period",
      "svrha",
      "perigej",
      "apogej"
    ]
  }
}

=== Luka-Sever/Otvoreno-ra-unarstvo/frontend/public/sateliti.json
[
    {
        "ime satelita": "AprizeSat 4",
        "drzava porijekla": "SAD",
        "drzava odrzavanja": "SAD/Argentina",
        "vlasnik": "Aprize Satelliti, Argentina",
        "korist": "Komercijalna",
        "orbita": "LEO",
        "inklinacija": 98.1,
        "period": 97.5,
        "svrha": "Komunikacija",
        "perigej": 604.0,
        "apogej": 674.0
    },
    {
        "ime satelita": "AprizeSat 4",
        "drzava porijekla": "SAD",
        "drzava odrzavanja": "SAD/Argentina",
        "vlasnik": "Aprize Satelliti, Argentina",
        "korist": "Komercijalna",
        "orbita": "LEO",
        "inklinacija": 98.1,
        "period": 97.5,
        "svrha": "Pomorsko praćenje",
        "perigej": 604.0,
        "apogej": 674.0
    },
    {
        "ime satelita": "Meteosat 9",
        "drzava porijekla": "EUMETSAT",
        "drzava odrzavanja": "Multinacionalna",
        "vlasnik": "EUMETSAT (European Organization for the Exploitation of Meteorological Satellites)",
        "korist": "Vladina/Civili",
        "orbita": "GEO",
        "inklinacija": 0.29,
        "period": 1436.0,
        "svrha": "Obzervacija Zemlje",
        "perigej": 35775.0,
        "apogej": 35795.0
    },
    {
        "ime satelita": "RISat-2B",
        "drzava porijekla": "Indija",
        "drzava odrzavanja": "Indija",
        "vlasnik": "Ministry of Defense",
        "korist": "Vojna",
        "orbita": "LEO",
        "inklinacija": 37.0,
        "period": 96.0,
        "svrha": "Obzervacija Zemlje",
        "perigej": 550.0,
        "apogej": 557.0
    },
    {
        "ime satelita": "Beidou DW 33",
        "drzava porijekla": "Kina",
        "drzava odrzavanja": "Kina",
        "vlasnik": "Chinese Ministry of National Defense",
        "korist": "Vojna/Vladina",
        "orbita": "MEO",
        "inklinacija": 55.0,
        "period": 773.2,
        "svrha": "Navigacija",
        "perigej": 21509.0,
        "apogej": 21545.0
    },
    {
        "ime satelita": "Beidou DW 33",
        "drzava porijekla": "Kina",
        "drzava odrzavanja": "Kina",
        "vlasnik": "Chinese Ministry of National Defense",
        "korist": "Vojna/Vladina",
        "orbita": "MEO",
        "inklinacija": 55.0,
        "period": 773.2,
        "svrha": "Globalna navigacija",
        "perigej": 21509.0,
        "apogej": 21545.0
    },
    {
        "ime satelita": "USA 262",
        "drzava porijekla": "SAD",
        "drzava odrzavanja": "SAD",
        "vlasnik": "DoD/US Air Force",
        "korist": "Vojna/Komercijalna",
        "orbita": "MEO",
        "inklinacija": 54.9,
        "period": 728.96,
        "svrha": "Navigacija",
        "perigej": 20446.0,
        "apogej": 20459.0
    },
    {
        "ime satelita": "USA 262",
        "drzava porijekla": "SAD",
        "drzava odrzavanja": "SAD",
        "vlasnik": "DoD/US Air Force",
        "korist": "Vojna/Komercijalna",
        "orbita": "MEO",
        "inklinacija": 54.9,
        "period": 728.96,
        "svrha": "Globalna navigacija",
        "perigej": 20446.0,
        "apogej": 20459.0
    },
    {
        "ime satelita": "Kepler-11 DANEEL",
        "drzava porijekla": "NR (5/21)",
        "drzava odrzavanja": "Kanada",
        "vlasnik": "Kepler Communications",
        "korist": "Komercijalna",
        "orbita": "LEO",
        "inklinacija": 97.7,
        "period": 95.2,
        "svrha": "Komunikacija",
        "perigej": 525.0,
        "apogej": 535.0
    },
    {
        "ime satelita": "Ladybird 2",
        "drzava porijekla": "NR",
        "drzava odrzavanja": "China",
        "vlasnik": "Beijing Commsat Technology Development Co. Ltd.",
        "korist": "Komercijalna",
        "orbita": "LEO",
        "inklinacija": 97.6,
        "period": 95.4,
        "svrha": "Unaprjeđivanje tehnologije",
        "perigej": 530.0,
        "apogej": 549.0
    },
    {
        "ime satelita": "PVSAT",
        "drzava porijekla": "NR (9/21)",
        "drzava odrzavanja": "Južna Koreja",
        "vlasnik": "Korean Aerospace Research Institute (KARI)",
        "korist": "Vladina",
        "orbita": "LEO",
        "inklinacija": 98.1,
        "period": 100.0,
        "svrha": "Demonstracija tehnologije",
        "perigej": 695.0,
        "apogej": 704.0
    },
    {
        "ime satelita": "Mercury 3",
        "drzava porijekla": "SAD",
        "drzava odrzavanja": "SAD",
        "vlasnik": "National Reconnaissance Office (NRO)/US Air Force",
        "korist": "Vojna",
        "orbita": "GEO",
        "inklinacija": 7.0,
        "period": 1436.0,
        "svrha": "Obzervacija Zemlje",
        "perigej": 35500.0,
        "apogej": 35500.0
    },
    {
        "ime satelita": "Lemur-2 AC-Cubed ",
        "drzava porijekla": "NR (9/21)",
        "drzava odrzavanja": "SAD",
        "vlasnik": "Spire Global Inc.",
        "korist": "Komercijalna",
        "orbita": "LEO",
        "inklinacija": 97.5,
        "period": 95.2,
        "svrha": "Obzervacija Zemlje",
        "perigej": 512.0,
        "apogej": 533.0
    }
]
